name: tile_map_builder
version: 0.0.0
description: A library which lets you convert text files into rich tile maps.
repository: https://github.com/chrisnorman7/tile_map_builder

environment:
  sdk: ^3.10.0-290.1.beta
dependencies:
  characters: ^1.4.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
scripts:
  clear:
    $script:
      $windows: cls
      default: clear
  test:
    $before: rps clear
    $script: dart test
