name: tile_map_builder
version: 0.0.1
description: A library which lets you convert text files into rich tile maps.
repository: https://github.com/chrisnorman7/tile_map_builder

environment:
  sdk: ^3.9.2
dependencies:
  characters: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
scripts:
  clear:
    $script:
      $windows: cls
      default: clear
  test:
    $before: rps clear
    $script: dart test
  ex: dart run example/tile_map_builder_example.dart
